import "./globals.css";
import { ReactNode } from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type RootProps = {
	children?: ReactNode;
}

export default function RootLayout(props: RootProps) {
	const { children } = props;

	return (
		<html lang="en">
		<body>{children}</body>
		</html>
	);
}
