name: 'setup-code'
description: 'Installs packages and runs foreground scripts'

inputs:
  GH_ACCESS_TOKEN:
    description: GitHub access token
    required: true
  WORKDIR:
    description: Working dir with package.json file
    required: true
    default: ./

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3.5.1
      id: setup-node
      with:
        node-version: '18.16'
        # The following key cache will be used `${{ runner.os }}-npm-${{ hashFiles('<package-lock-path>') }}`
        # https://github.com/actions/setup-node/blob/3ae886ede4e5ed7ca0b68ff6124d681158afe891/docs/adrs/0000-caching-dependencies.md?plain=1#L28
        cache: 'yarn'
        cache-dependency-path: ${{ inputs.WORKDIR }}/yarn.lock

    - if: steps.setup-node.outputs.cache-hit != 'true'
      name: List the state of node modules
      working-directory: ${{ inputs.WORKDIR }}
      shell: bash
      continue-on-error: true
      run: yarn list

    - name: Install NPM modules
      working-directory: ${{ inputs.WORKDIR }}
      shell: bash
      run: yarn install
      env:
        NODE_AUTH_TOKEN: ${{ inputs.GH_ACCESS_TOKEN }}
